Hw5 готово для проверки
Xpom3000/homework1 pull request #9
Opened 2023-11-05 19:41 UTC by Xpom3000

2023-11-06 18:59 UTC, Mielilon requested changes

2023-11-06 18:59 UTC, Mielilon commented on site/script.js
> +    function printMessage() {
Не совсем верное решение. Функция `printMessage` должна быть оберткой для условий, а не наоборот. Нужно создать функцию и в нее поместить условия с возвращением строк.

2023-11-06 18:59 UTC, Mielilon commented on site/script.js
> +    function printMessage() {
Опять же, функция `printMessage` объявлена неправильно. Должна быть **одна** функция, которая принимает возраст и возвращает соответствующее сообщение. Все условия должны находиться внутри этой функции.

2023-11-06 18:59 UTC, Mielilon commented on site/script.js
> +} if (0 < num1 <= 12) {
Когда вы пишете `0 < num1 <= 12`, JavaScript интерпретирует это следующим образом:

1. Сначала проверяется условие 0 < num1. Если num1 больше 0, то результат этого выражения будет true.
2. Затем true приводится к числу в следующем сравнении, где true становится 1, и 1 <= 12 всегда истинно, независимо от значения num1. Если num1 меньше или равно 0, то false приводится к 0, и 0 <= 12 также истинно.
3. Правильный способ записи условия, когда вы хотите проверить, что num1 находится в диапазоне между двумя числами, выглядит так:
```
if (num1 > 0 && num1 <= 12) {
  // ... ваш код ...
}
```
В этой конструкции `&&` означает логическое "И", и обе части условия должны быть истинными, чтобы выполнить код внутри блока `if`.

2023-11-06 18:59 UTC, Mielilon commented on site/script.js
> +    if ( isNaN(a && b)) {
`isNaN` принимает только одно значение, нужно исправить.

2023-11-06 18:59 UTC, Mielilon commented on site/script.js
> +    } if(n >= 0 && n <= 10) {
Тут возвращается куб числа только для диапазона от 0 до 10, но по условию задания, проверка должна производиться **только** на корректность числа.

2023-11-06 18:59 UTC, Mielilon commented on site/script.js
> +alert('Задание 7');
Задание 7 не было решено, пожалуйста, добавьте его в проект.

2023-11-06 21:19 UTC, Xpom3000 commented on site/script.js
> +    } if(n >= 0 && n <= 10) {
Задание 6
Проверьте самостоятельно, что данная функция работает корректно и выводит правильный результат с параметрами 
**от 0 до 10** включительно.
Вот условие задания на диапазон. Или я не так понял?

2023-11-06 22:40 UTC, Xpom3000 commented on site/script.js
> +    function printMessage() {
исправил

2023-11-06 22:40 UTC, Xpom3000 commented on site/script.js
> +    function printMessage() {
Исправил

2023-11-06 22:41 UTC, Xpom3000 commented on site/script.js
> +} if (0 < num1 <= 12) {
Исправил

2023-11-08 20:29 UTC, Xpom3000 commented on site/script.js
> +    if ( isNaN(a && b)) {
Исправил

2023-11-09 19:18 UTC, merged